.PHONY: build clean

build:
	@mvn verify

clean:
	@mvn clean

##THIS="serverside-todomvc-java-wicket"
##HERE=`pwd`
##THERE="${HERE}/../"
##export URL="http://localhost:8080/${THIS}/"
##
##build:
##	@mvn verify -pl ${THIS} -am
##
##test:
##	@java -jar target/*.jar
##	$(MAKE) -C ${THERE} test
