###
### Server-side TodoMVC - Java Examples - Servlet
###
### Builds and tests the servlet application using an acceptance testing
### profile, starting the web app and executing the acceptance tests
### against it.
###
.PHONY: all

all:
	@mvn clean verify
